"""Purpose: Define shared presentation helpers for Streamlit pages."""

from __future__ import annotations

from html import escape
from typing import Iterable

import streamlit as st

from backend.models.dashboard import DashboardMetric


def render_page_header(title: str, description: str) -> None:
    """Render a consistent page heading block.

    Args:
        title: Main page title.
        description: Supporting page description.
    """
    st.title(title)
    st.caption(description)


def render_html_block(markup: str) -> None:
    """Render trusted HTML markup for custom card layouts.

    Args:
        markup: HTML content generated by the application.
    """
    st.markdown(markup, unsafe_allow_html=True)


def render_metric_cards(metrics: Iterable[DashboardMetric]) -> None:
    """Display dashboard metrics in a compact card layout.

    Args:
        metrics: Metrics to render.
    """
    metric_markup = "".join(
        f"""
        <div class="soc-kpi-card">
          <div class="soc-kpi-label">{escape(metric.label)}</div>
          <div class="soc-kpi-value">{escape(metric.value)}</div>
          <div class="soc-kpi-delta">{escape(metric.delta or "Scaffold metric")}</div>
        </div>
        """
        for metric in metrics
    )
    render_html_block(f'<div class="soc-kpi-grid">{metric_markup}</div>')


def render_placeholder_notice(title: str, body: str) -> None:
    """Display a clearly marked placeholder section.

    Args:
        title: Notice heading.
        body: Supporting explanation.
    """
    st.info(f"**{title}**\n\n{body}")


def render_stat_list(items: list[tuple[str, str]]) -> None:
    """Render a compact list of key-value pairs.

    Args:
        items: Ordered label/value pairs.
    """
    item_markup = "".join(
        f"<li><span>{escape(label)}</span><strong>{escape(value)}</strong></li>"
        for label, value in items
    )
    render_html_block(f'<ul class="soc-list">{item_markup}</ul>')
