"""Purpose: Define shared presentation helpers for Streamlit pages."""

from __future__ import annotations

from html import escape
from typing import Iterable, Mapping, Sequence

import streamlit as st

from backend.models.dashboard import DashboardMetric
from db.models.enums import AlertStatusEnum

ALERT_STATUS_DISPLAY: dict[AlertStatusEnum, str] = {
    AlertStatusEnum.NEW: "New",
    AlertStatusEnum.IN_PROGRESS: "Investigating",
    AlertStatusEnum.CLOSED: "Resolved",
    AlertStatusEnum.FALSE_POSITIVE: "False Positive",
}

ALERT_STATUS_FROM_DISPLAY: dict[str, AlertStatusEnum] = {
    label: status for status, label in ALERT_STATUS_DISPLAY.items()
}


def render_page_header(title: str, description: str) -> None:
    """Render a consistent page heading block.

    Args:
        title: Main page title.
        description: Supporting page description.
    """
    st.title(title)
    st.caption(description)


def dedent_html(markup: str) -> str:
    """Strip per-line leading whitespace so markdown never mistakes HTML for a code block.

    CommonMark treats any line indented 4+ spaces as an indented code block. Multi-line
    f-string HTML templates are written with readable indentation, so leading whitespace
    must be normalized before handing the markup to ``st.markdown``.

    Args:
        markup: Raw HTML markup, possibly indented for source readability.

    Returns:
        The same markup with leading whitespace removed from every line.
    """
    return "\n".join(line.strip() for line in markup.strip("\n").splitlines())


def render_html_block(markup: str) -> None:
    """Render trusted HTML markup for custom card layouts.

    Args:
        markup: HTML content generated by the application.
    """
    st.markdown(dedent_html(markup), unsafe_allow_html=True)


def render_metric_cards(metrics: Iterable[DashboardMetric]) -> None:
    """Display dashboard metrics in a compact card layout.

    Args:
        metrics: Metrics to render.
    """
    metric_markup = "".join(
        f"""
        <div class="soc-kpi-card">
          <div class="soc-kpi-label">{escape(metric.label)}</div>
          <div class="soc-kpi-value">{escape(metric.value)}</div>
          <div class="soc-kpi-delta">{escape(metric.delta or "Scaffold metric")}</div>
        </div>
        """
        for metric in metrics
    )
    render_html_block(f'<div class="soc-kpi-grid">{metric_markup}</div>')


def render_placeholder_notice(title: str, body: str) -> None:
    """Display a clearly marked placeholder section.

    Args:
        title: Notice heading.
        body: Supporting explanation.
    """
    st.info(f"**{title}**\n\n{body}")


def render_stat_list(items: list[tuple[str, str]]) -> None:
    """Render a compact list of key-value pairs.

    Args:
        items: Ordered label/value pairs.
    """
    item_markup = "".join(
        f"<li><span>{escape(label)}</span><strong>{escape(value)}</strong></li>"
        for label, value in items
    )
    render_html_block(f'<ul class="soc-list">{item_markup}</ul>')


def severity_badge(severity: str) -> str:
    """Build markup for a severity badge.

    Args:
        severity: Severity label (Critical, High, Medium, Low).

    Returns:
        HTML span markup for the badge.
    """
    slug = severity.strip().lower()
    return f'<span class="soc-severity-badge severity-{escape(slug)}">{escape(severity)}</span>'


def status_badge(status: str) -> str:
    """Build markup for a status badge.

    Args:
        status: Status label (New, Investigating, Contained, Resolved, Draft, Completed).

    Returns:
        HTML span markup for the badge.
    """
    slug = status.strip().lower().replace(" ", "-")
    return f'<span class="soc-status-badge status-{escape(slug)}">{escape(status)}</span>'


def render_metric_grid(metrics: Sequence[Mapping[str, str]], columns: int = 4) -> None:
    """Render compact metric/KPI cards in a responsive grid.

    Args:
        metrics: Sequence of dicts with ``label``, ``value``, and optional ``delta``.
        columns: Number of grid columns (rendered via CSS custom var override).
    """
    cards = "".join(
        f"""
        <div class="soc-kpi-card">
          <div class="soc-kpi-label">{escape(str(metric.get('label', '')))}</div>
          <div class="soc-kpi-value">{escape(str(metric.get('value', '')))}</div>
          <div class="soc-kpi-delta">{escape(str(metric.get('delta', '')))}</div>
        </div>
        """
        for metric in metrics
    )
    render_html_block(
        f'<div class="soc-kpi-grid" style="grid-template-columns: repeat({columns}, minmax(0,1fr));">{cards}</div>'
    )


def render_data_table(
    columns: Sequence[str],
    rows: Sequence[Mapping[str, str]],
    keys: Sequence[str] | None = None,
    severity_key: str | None = None,
    status_key: str | None = None,
    mono_keys: Sequence[str] = (),
    strong_keys: Sequence[str] = (),
) -> None:
    """Render a compact, professional HTML data table with badge support.

    Args:
        columns: Column header labels, in display order.
        rows: Row data as dicts.
        keys: Dict keys to pull per column, matching ``columns`` order. Defaults to
            lowercased, space-joined column names.
        severity_key: Row key whose value should render as a severity badge.
        status_key: Row key whose value should render as a status badge.
        mono_keys: Row keys that should render in monospace (IPs, hashes, IDs).
        strong_keys: Row keys that should render with emphasis.
    """
    resolved_keys = keys or [col.lower().replace(" ", "_") for col in columns]
    header_markup = "".join(f"<th>{escape(col)}</th>" for col in columns)

    body_rows = []
    for row in rows:
        cells = []
        for col, key in zip(columns, resolved_keys):
            value = str(row.get(key, ""))
            if key == severity_key:
                cells.append(f"<td>{severity_badge(value)}</td>")
            elif key == status_key:
                cells.append(f"<td>{status_badge(value)}</td>")
            else:
                css_class = " ".join(
                    filter(None, ["mono" if key in mono_keys else "", "strong" if key in strong_keys else ""])
                )
                class_attr = f' class="{css_class}"' if css_class else ""
                cells.append(f"<td{class_attr}>{escape(value)}</td>")
        body_rows.append(f"<tr>{''.join(cells)}</tr>")

    render_html_block(
        f"""
        <div class="soc-table-wrap">
          <table class="soc-table">
            <thead><tr>{header_markup}</tr></thead>
            <tbody>{''.join(body_rows)}</tbody>
          </table>
        </div>
        """
    )


def render_risk_gauge(score: int, label: str) -> None:
    """Render a risk score gauge with a labeled progress bar.

    Args:
        score: Risk score out of 100.
        label: Risk tier label, e.g. "HIGH RISK".
    """
    tier = "low"
    if score >= 80:
        tier = "critical"
    elif score >= 60:
        tier = "high"
    elif score >= 35:
        tier = "medium"

    render_html_block(
        f"""
        <div class="soc-risk-gauge">
          <div class="soc-risk-score">{score}<span>/100</span></div>
          <div class="soc-risk-gauge-bar">
            <div class="soc-risk-gauge-track">
              <div class="soc-risk-gauge-fill risk-{tier}" style="width: {min(score, 100)}%;"></div>
            </div>
            <div class="soc-risk-gauge-label">{escape(label)}</div>
          </div>
        </div>
        """
    )


def render_timeline(events: Sequence[Mapping[str, str]]) -> None:
    """Render a vertical security-event timeline.

    Args:
        events: Sequence of dicts with ``time``, ``event``, and optional ``detail``.
    """
    items = "".join(
        f"""
        <div class="soc-timeline-item">
          <div class="soc-timeline-time">{escape(str(event.get('time', '')))}</div>
          <div class="soc-timeline-event">{escape(str(event.get('event', '')))}</div>
          <div class="soc-timeline-detail">{escape(str(event.get('detail', '')))}</div>
        </div>
        """
        for event in events
    )
    render_html_block(f'<div class="soc-timeline">{items}</div>')


def render_ioc_chips(iocs: Sequence[Mapping[str, str]]) -> None:
    """Render indicators of compromise as labeled chips.

    Args:
        iocs: Sequence of dicts with ``type`` and ``value``.
    """
    chips = "".join(
        f"""
        <div class="soc-ioc-chip">
          <div class="soc-ioc-chip-label">{escape(str(ioc.get('type', '')))}</div>
          <div class="soc-ioc-chip-value">{escape(str(ioc.get('value', '')))}</div>
        </div>
        """
        for ioc in iocs
    )
    render_html_block(f'<div class="soc-chip-list">{chips}</div>')


def render_tag_list(tags: Iterable[str]) -> None:
    """Render a simple wrapped list of text tags.

    Args:
        tags: Tag labels to render.
    """
    tag_markup = "".join(f'<span class="soc-tag">{escape(tag)}</span>' for tag in tags)
    render_html_block(f'<div class="soc-tag-list">{tag_markup}</div>')


def render_checklist(items: Sequence[str], key_prefix: str) -> None:
    """Render an interactive investigation checklist.

    Args:
        items: Checklist item labels.
        key_prefix: Unique prefix for Streamlit widget state keys.
    """
    for index, item in enumerate(items):
        st.checkbox(item, key=f"{key_prefix}_{index}")


def render_bullet_list(items: Iterable[str]) -> None:
    """Render a simple bulleted list using the shared visual style.

    Args:
        items: Bullet text items.
    """
    list_markup = "".join(f"<li>{escape(item)}</li>" for item in items)
    render_html_block(f'<ul class="soc-bullets">{list_markup}</ul>')


def render_integration_cards(integrations: Sequence[Mapping[str, str]]) -> None:
    """Render integration/platform availability cards.

    Args:
        integrations: Sequence of dicts with ``name``, ``category``, and ``status``.
    """
    status_class = {
        "Available": "available",
        "Available Soon": "soon",
    }
    cards = "".join(
        f"""
        <div class="soc-integration-card">
          <div class="soc-integration-name">{escape(str(item.get('name', '')))}</div>
          <div class="soc-integration-category">{escape(str(item.get('category', '')))}</div>
          <div class="soc-integration-status {status_class.get(str(item.get('status', '')), '')}">
            {escape(str(item.get('status', '')))}
          </div>
        </div>
        """
        for item in integrations
    )
    render_html_block(f'<div class="soc-integration-grid">{cards}</div>')


def render_empty_state(title: str, body: str) -> None:
    """Render a centered empty-state block.

    Args:
        title: Empty state heading.
        body: Supporting copy.
    """
    render_html_block(
        f"""
        <div class="soc-empty-state">
          <div class="soc-empty-state-title">{escape(title)}</div>
          <div>{escape(body)}</div>
        </div>
        """
    )
