"""initial schema

Revision ID: 88a1df0e92a3
Revises: 
Create Date: 2026-08-19 04:23:08.337085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a1df0e92a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severityenum', native_enum=False), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'CLOSED', 'FALSE_POSITIVE', name='alertstatusenum', native_enum=False), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('rule_id', sa.String(length=255), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('destination_ip', sa.String(length=45), nullable=True),
    sa.Column('mitre_tactic', sa.String(length=255), nullable=True),
    sa.Column('mitre_technique_id', sa.String(length=50), nullable=True),
    sa.Column('mitre_technique_name', sa.String(length=255), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts')),
    sa.UniqueConstraint('external_id', name=op.f('uq_alerts_external_id'))
    )
    op.create_index('ix_alerts_first_seen', 'alerts', ['first_seen'], unique=False)
    op.create_index('ix_alerts_hostname', 'alerts', ['hostname'], unique=False)
    op.create_index('ix_alerts_last_seen', 'alerts', ['last_seen'], unique=False)
    op.create_index('ix_alerts_mitre_tactic', 'alerts', ['mitre_tactic'], unique=False)
    op.create_index('ix_alerts_mitre_technique_id', 'alerts', ['mitre_technique_id'], unique=False)
    op.create_index('ix_alerts_rule_id', 'alerts', ['rule_id'], unique=False)
    op.create_index('ix_alerts_severity', 'alerts', ['severity'], unique=False)
    op.create_index('ix_alerts_source', 'alerts', ['source'], unique=False)
    op.create_index('ix_alerts_source_ip', 'alerts', ['source_ip'], unique=False)
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_username', 'alerts', ['username'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='casestatusenum', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='casepriorityenum', native_enum=False), nullable=False),
    sa.Column('assignee', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases')),
    sa.UniqueConstraint('case_number', name=op.f('uq_cases_case_number'))
    )
    op.create_index('ix_cases_assignee', 'cases', ['assignee'], unique=False)
    op.create_index('ix_cases_priority', 'cases', ['priority'], unique=False)
    op.create_index('ix_cases_status', 'cases', ['status'], unique=False)
    op.create_table('detection_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severityenum', native_enum=False), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('mitre_tactic', sa.String(length=255), nullable=True),
    sa.Column('mitre_technique_id', sa.String(length=50), nullable=True),
    sa.Column('mitre_technique_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detection_rules')),
    sa.UniqueConstraint('name', name=op.f('uq_detection_rules_name'))
    )
    op.create_index('ix_detection_rules_enabled', 'detection_rules', ['enabled'], unique=False)
    op.create_index('ix_detection_rules_mitre_tactic', 'detection_rules', ['mitre_tactic'], unique=False)
    op.create_index('ix_detection_rules_mitre_technique_id', 'detection_rules', ['mitre_technique_id'], unique=False)
    op.create_index('ix_detection_rules_severity', 'detection_rules', ['severity'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('dataset', sa.String(length=255), nullable=True),
    sa.Column('event_category', sa.String(length=255), nullable=True),
    sa.Column('event_action', sa.String(length=255), nullable=True),
    sa.Column('event_outcome', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('source_port', sa.Integer(), nullable=True),
    sa.Column('destination_ip', sa.String(length=45), nullable=True),
    sa.Column('destination_port', sa.Integer(), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('process_name', sa.String(length=255), nullable=True),
    sa.Column('process_command_line', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('raw_event', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index('ix_events_destination_ip', 'events', ['destination_ip'], unique=False)
    op.create_index('ix_events_event_category', 'events', ['event_category'], unique=False)
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=True)
    op.create_index('ix_events_hostname', 'events', ['hostname'], unique=False)
    op.create_index('ix_events_severity', 'events', ['severity'], unique=False)
    op.create_index('ix_events_source', 'events', ['source'], unique=False)
    op.create_index('ix_events_source_ip', 'events', ['source_ip'], unique=False)
    op.create_index('ix_events_timestamp', 'events', ['timestamp'], unique=False)
    op.create_index('ix_events_username', 'events', ['username'], unique=False)
    op.create_table('alert_event',
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_alert_event_alert_id_alerts')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_alert_event_event_id_events')),
    sa.PrimaryKeyConstraint('alert_id', 'event_id', name=op.f('pk_alert_event'))
    )
    op.create_table('case_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_case_activities_case_id_cases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_activities'))
    )
    op.create_index(op.f('ix_case_activities_case_id'), 'case_activities', ['case_id'], unique=False)
    op.create_table('case_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_case_alerts_alert_id_alerts')),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_case_alerts_case_id_cases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_alerts')),
    sa.UniqueConstraint('case_id', 'alert_id', name='uq_case_alerts_case_id_alert_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_alerts')
    op.drop_index(op.f('ix_case_activities_case_id'), table_name='case_activities')
    op.drop_table('case_activities')
    op.drop_table('alert_event')
    op.drop_index('ix_events_username', table_name='events')
    op.drop_index('ix_events_timestamp', table_name='events')
    op.drop_index('ix_events_source_ip', table_name='events')
    op.drop_index('ix_events_source', table_name='events')
    op.drop_index('ix_events_severity', table_name='events')
    op.drop_index('ix_events_hostname', table_name='events')
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.drop_index('ix_events_event_category', table_name='events')
    op.drop_index('ix_events_destination_ip', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_detection_rules_severity', table_name='detection_rules')
    op.drop_index('ix_detection_rules_mitre_technique_id', table_name='detection_rules')
    op.drop_index('ix_detection_rules_mitre_tactic', table_name='detection_rules')
    op.drop_index('ix_detection_rules_enabled', table_name='detection_rules')
    op.drop_table('detection_rules')
    op.drop_index('ix_cases_status', table_name='cases')
    op.drop_index('ix_cases_priority', table_name='cases')
    op.drop_index('ix_cases_assignee', table_name='cases')
    op.drop_table('cases')
    op.drop_index('ix_alerts_username', table_name='alerts')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index('ix_alerts_source_ip', table_name='alerts')
    op.drop_index('ix_alerts_source', table_name='alerts')
    op.drop_index('ix_alerts_severity', table_name='alerts')
    op.drop_index('ix_alerts_rule_id', table_name='alerts')
    op.drop_index('ix_alerts_mitre_technique_id', table_name='alerts')
    op.drop_index('ix_alerts_mitre_tactic', table_name='alerts')
    op.drop_index('ix_alerts_last_seen', table_name='alerts')
    op.drop_index('ix_alerts_hostname', table_name='alerts')
    op.drop_index('ix_alerts_first_seen', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
